name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release
  VCPKG_COMMIT: 6f29f12e82a8293156836ad81cc9bf5af41fe836

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      # https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      # https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: actions/checkout@v4
        with:
          repository: Microsoft/vcpkg
          path: vcpkg
          ref: ${{ env.VCPKG_COMMIT }}

      - name: Install vcpkg
        working-directory: ${{github.workspace}}/vcpkg
        run: |
          .\bootstrap-vcpkg.bat

      # Build the game
      - uses: actions/checkout@v4
        with:
          path: ggj2025
          submodules: recursive

      - name: Configure game
        run: cmake -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_UNITY_BUILD=ON -T host=x64 -A x64 -S ${{github.workspace}}/ggj2025/ -B ${{github.workspace}}/ggj2025/build

      - name: Build game
        run: cmake --build ${{github.workspace}}/ggj2025/build --config ${{env.BUILD_TYPE}} --parallel

      - name: Create game
        working-directory: ${{github.workspace}}/ggj2025/build
        run: cpack --config CPackConfig.cmake -C ${{env.BUILD_TYPE}}

      - uses: actions/upload-artifact@v4
        with:
          name: ggj2025-snapshot
          path: ${{github.workspace}}/ggj2025/build/*.zip
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-22.04

    steps:
      # Dependencies
      - name: Install dependency
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev libboost-dev libfreetype6-dev zlib1g-dev libpugixml-dev libsfml-dev libchipmunk-dev

      # Build the game
      - uses: actions/checkout@v4
        with:
          path: ggj2025
          submodules: recursive

      - name: Configure ggj2025
        run: cmake -DCMAKE_UNITY_BUILD=ON -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S ${{github.workspace}}/ggj2025/ -B ${{github.workspace}}/ggj2025/build

      - name: Build ggj2025
        run: cmake --build ${{github.workspace}}/ggj2025/build --config ${{env.BUILD_TYPE}} --parallel
